<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class DistrictSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $districts = [
            ['id' => 1, 'name' => 'လယ်ဝေး', 'region_id' => 1],
            ['id' => 2, 'name' => 'ပျဥ်းမနား', 'region_id' => 1],
            ['id' => 3, 'name' => 'ဥတ္တရ', 'region_id' => 1],
            ['id' => 4, 'name' => 'ဇေယျာသီရိ', 'region_id' => 1],
            ['id' => 5, 'name' => 'ပူတာအို', 'region_id' => 2],
            ['id' => 6, 'name' => 'ဗန်းမော်', 'region_id' => 2],
            ['id' => 7, 'name' => 'မိုးညှင်း', 'region_id' => 2],
            ['id' => 8, 'name' => 'မြစ်ကြီးနား', 'region_id' => 2],
            ['id' => 9, 'name' => 'တနိုင်း', 'region_id' => 2],
            ['id' => 10, 'name' => 'ချီဖွေ', 'region_id' => 2],
            ['id' => 11, 'name' => 'လွိုင်ကော်', 'region_id' => 3],
            ['id' => 12, 'name' => 'ဒီးမော့ဆို', 'region_id' => 3],
            ['id' => 13, 'name' => 'ဘောလခဲ', 'region_id' => 3],
            ['id' => 14, 'name' => 'မယ်စဲ့', 'region_id' => 3],
            ['id' => 15, 'name' => 'ကော့ကရိတ်', 'region_id' => 4],
            ['id' => 16, 'name' => 'ကြာအင်းဆိပ်ကြီး', 'region_id' => 4],
            ['id' => 17, 'name' => 'ဖာပွန်', 'region_id' => 4],
            ['id' => 18, 'name' => 'ဘားအံ', 'region_id' => 4],
            ['id' => 19, 'name' => 'သံတောင်ကြီး', 'region_id' => 4],
            ['id' => 20, 'name' => 'မြဝတီ', 'region_id' => 4],
            ['id' => 21, 'name' => 'ဖလမ်း', 'region_id' => 5],
            ['id' => 22, 'name' => 'တီးတိန်', 'region_id' => 5],
            ['id' => 23, 'name' => 'မတူပီ', 'region_id' => 5],
            ['id' => 24, 'name' => 'ပလက်ဝ', 'region_id' => 5],
            ['id' => 25, 'name' => 'မင်းတပ်', 'region_id' => 5],
            ['id' => 26, 'name' => 'ဟားခါး', 'region_id' => 5],
            ['id' => 27, 'name' => 'နာဂ ကိုယ်ပိုင်အုပ်ချုပ်ခွင့်ရဒေသ', 'region_id' => 6],
            ['id' => 28, 'name' => 'ကလေး', 'region_id' => 6],
            ['id' => 29, 'name' => 'ကသာ', 'region_id' => 6],
            ['id' => 30, 'name' => 'ကောလင်း', 'region_id' => 6],
            ['id' => 31, 'name' => 'ကန့်ဘလူ', 'region_id' => 6],
            ['id' => 32, 'name' => 'ခန္တီး', 'region_id' => 6],
            ['id' => 33, 'name' => 'ဟုမ္မလင်း', 'region_id' => 6],
            ['id' => 34, 'name' => 'စစ်ကိုင်း', 'region_id' => 6],
            ['id' => 35, 'name' => 'တမူး', 'region_id' => 6],
            ['id' => 36, 'name' => 'မုံရွာ', 'region_id' => 6],
            ['id' => 37, 'name' => 'မော်လိုက်', 'region_id' => 6],
            ['id' => 38, 'name' => 'ယင်းမာပြင်', 'region_id' => 6],
            ['id' => 39, 'name' => 'ရွှေဘို', 'region_id' => 6],
            ['id' => 40, 'name' => 'ရေဦး', 'region_id' => 6],
            ['id' => 41, 'name' => 'ကော့သောင်း', 'region_id' => 7],
            ['id' => 42, 'name' => 'ဘုတ်ပြင်း', 'region_id' => 7],
            ['id' => 43, 'name' => 'ထားဝယ်', 'region_id' => 7],
            ['id' => 44, 'name' => 'မြိတ်', 'region_id' => 7],
            ['id' => 45, 'name' => 'တောင်ငူ', 'region_id' => 8],
            ['id' => 46, 'name' => 'ပဲခူး', 'region_id' => 8],
            ['id' => 47, 'name' => 'ညောင်လေးပင်', 'region_id' => 8],
            ['id' => 48, 'name' => 'ပြည်', 'region_id' => 8],
            ['id' => 49, 'name' => 'သာယာဝတီ', 'region_id' => 8],
            ['id' => 50, 'name' => 'နတ်တလင်း', 'region_id' => 8],
            ['id' => 51, 'name' => 'ဂန့်ဂေါ', 'region_id' => 9],
            ['id' => 52, 'name' => 'ပခုက္ကူ', 'region_id' => 9],
            ['id' => 53, 'name' => 'မကွေး', 'region_id' => 9],
            ['id' => 54, 'name' => 'ချောက်', 'region_id' => 9],
            ['id' => 55, 'name' => 'မင်းဘူး', 'region_id' => 9],
            ['id' => 56, 'name' => 'သရက်', 'region_id' => 9],
            ['id' => 57, 'name' => 'အောင်လံ', 'region_id' => 9],
            ['id' => 58, 'name' => 'ကျောက်ဆည်', 'region_id' => 10],
            ['id' => 59, 'name' => 'တံတားဦး', 'region_id' => 10],
            ['id' => 60, 'name' => 'ညောင်ဦး', 'region_id' => 10],
            ['id' => 61, 'name' => 'ပြင်ဦးလွင်', 'region_id' => 10],
            ['id' => 62, 'name' => 'သပိတ်ကျင်း', 'region_id' => 10],
            ['id' => 63, 'name' => 'မဟာအောင်မြေ', 'region_id' => 10],
            ['id' => 64, 'name' => 'အောင်မြေသာဇံ', 'region_id' => 10],
            ['id' => 65, 'name' => 'အမရပူရ', 'region_id' => 10],
            ['id' => 66, 'name' => 'မိတ္ထီလာ', 'region_id' => 10],
            ['id' => 67, 'name' => 'မြင်းခြံ', 'region_id' => 10],
            ['id' => 68, 'name' => 'ရမည်းသင်း', 'region_id' => 10],
            ['id' => 69, 'name' => 'မော်လမြိုင်', 'region_id' => 11],
            ['id' => 70, 'name' => 'ရေး', 'region_id' => 11],
            ['id' => 71, 'name' => 'သထုံ', 'region_id' => 11],
            ['id' => 72, 'name' => 'ကျိုက်ထို', 'region_id' => 11],
            ['id' => 73, 'name' => 'ကျောက်ဖြူ', 'region_id' => 12],
            ['id' => 74, 'name' => 'အမ်း', 'region_id' => 12],
            ['id' => 75, 'name' => 'စစ်တွေ', 'region_id' => 12],
            ['id' => 76, 'name' => 'မောင်တော', 'region_id' => 12],
            ['id' => 77, 'name' => 'မြောက်ဦး', 'region_id' => 12],
            ['id' => 78, 'name' => 'သံတွဲ', 'region_id' => 12],
            ['id' => 79, 'name' => 'တောင်ကုတ်', 'region_id' => 12],
            ['id' => 80, 'name' => 'တိုက်ကြီး', 'region_id' => 13],
            ['id' => 81, 'name' => 'လှည်းကူး', 'region_id' => 13],
            ['id' => 82, 'name' => 'မှော်ဘီ', 'region_id' => 13],
            ['id' => 83, 'name' => 'မင်္ဂလာဒုံ', 'region_id' => 13],
            ['id' => 84, 'name' => 'အင်းစိန်', 'region_id' => 13],
            ['id' => 85, 'name' => 'သင်္ဃန်းကျွန်း', 'region_id' => 13],
            ['id' => 86, 'name' => 'ဗိုလ်တထောင်', 'region_id' => 13],
            ['id' => 87, 'name' => 'ဒဂုံမြို့သစ်', 'region_id' => 13],
            ['id' => 88, 'name' => 'သန်လျင်', 'region_id' => 13],
            ['id' => 89, 'name' => 'တွံတေး', 'region_id' => 13],
            ['id' => 90, 'name' => 'ကျောက်တံတား', 'region_id' => 13],
            ['id' => 91, 'name' => 'အလုံ', 'region_id' => 13],
            ['id' => 92, 'name' => 'မရမ်းကုန်း', 'region_id' => 13],
            ['id' => 93, 'name' => 'ကမာရွတ်', 'region_id' => 13],
            ['id' => 94, 'name' => 'မက်မန်း', 'region_id' => 14],
            ['id' => 95, 'name' => 'ဟိုပန်', 'region_id' => 14],
            ['id' => 96, 'name' => 'ဓနု(ကအဒ)', 'region_id' => 14],
            ['id' => 97, 'name' => 'ပအိုင်း(ကအဒ)', 'region_id' => 14],
            ['id' => 98, 'name' => 'ပလောင်(ကအဒ)', 'region_id' => 14],
            ['id' => 99, 'name' => 'ကိုးကန့်(ကအဒ)', 'region_id' => 14],
            ['id' => 100, 'name' => 'ကျောက်မဲ', 'region_id' => 14],
            ['id' => 101, 'name' => 'ကျိုင်းတုံ', 'region_id' => 14],
            ['id' => 102, 'name' => 'မိုင်းယန်း', 'region_id' => 14],
            ['id' => 103, 'name' => 'မိုင်းလား', 'region_id' => 14],
            ['id' => 104, 'name' => 'တာချီလိတ်', 'region_id' => 14],
            ['id' => 105, 'name' => 'မိုင်းယောင်း', 'region_id' => 14],
            ['id' => 106, 'name' => 'တောင်ကြီး', 'region_id' => 14],
            ['id' => 107, 'name' => 'ကလော', 'region_id' => 14],
            ['id' => 108, 'name' => 'မူဆယ်', 'region_id' => 14],
            ['id' => 109, 'name' => 'ကွတ်ခိုင်', 'region_id' => 14],
            ['id' => 110, 'name' => 'မိုးမိတ်', 'region_id' => 14],
            ['id' => 111, 'name' => 'မိူင်းဆတ်', 'region_id' => 14],
            ['id' => 112, 'name' => 'မိုင်းတုံ', 'region_id' => 14],
            ['id' => 113, 'name' => 'လားရှိုး', 'region_id' => 14],
            ['id' => 114, 'name' => 'တန့်ယန်း', 'region_id' => 14],
            ['id' => 115, 'name' => 'လင်းခေး', 'region_id' => 14],
            ['id' => 116, 'name' => 'လွိုင်လင်', 'region_id' => 14],
            ['id' => 117, 'name' => 'နမ့်စန်', 'region_id' => 14],
            ['id' => 118, 'name' => 'မိုင်းရှူး', 'region_id' => 14],
            ['id' => 119, 'name' => 'ပုသိမ်', 'region_id' => 15],
            ['id' => 120, 'name' => 'ကျုံပျော်', 'region_id' => 15],
            ['id' => 121, 'name' => 'ဖျာပုံ', 'region_id' => 15],
            ['id' => 122, 'name' => 'မအူပင်', 'region_id' => 15],
            ['id' => 123, 'name' => 'မြောင်းမြ', 'region_id' => 15],
            ['id' => 124, 'name' => 'လပွတ္တာ', 'region_id' => 15],
            ['id' => 125, 'name' => 'ဟင်္သာတ', 'region_id' => 15],
            ['id' => 126, 'name' => 'မြန်အောင်', 'region_id' => 15],
        ];
        DB::table('districts')->insert($districts);
    }
}
