<?php

namespace Database\Seeders;

use App\Models\Education;
use App\Models\EducationType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

class EducationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Schema::disableForeignKeyConstraints();
        Education::truncate();
        Schema::enableForeignKeyConstraints();

$columns = [ 'name', 'education_type_id'];
$items = [
[ 'မူလတန်း','1'],
[ 'အလယ်တန်း','2'],
[ 'အထက်တန်း','3'],
[ 'B.A (Business Science)','4'],
[ 'B.A (Music)','4'],
[ 'B.A (Dramatic Arts)','4'],
[ 'B.A (Painting)','4'],
[ 'B.A (Sculpture)','4'],
[ 'B.A (Cinematography & Drama)','4'],
[ 'B.A (Myanmar)','4'],
[ 'B.A (English)','4'],
[ 'B.A (Geography)','4'],
[ 'B.A (History)','4'],
[ 'B.A (Oriental Studies)','4'],
[ 'B.A (Philosophy)','4'],
[ 'B.A (Psychology)','4'],
[ 'B.A (Anthropology)','4'],
[ 'B.A (Archaeology)','4'],
[ 'B.A (Business Management)','4'],
[ 'B.A (Chinese)','4'],
[ 'B.A (French)','4'],
[ 'B.A (German)','4'],
[ 'B.A (Japanese)','4'],
[ 'B.A (Korean)','4'],
[ 'B.A (Thai)','4'],
[ 'B.A (Journalism)','4'],
[ 'B.A (Creative Writing)','4'],
[ 'B.A (Economics)','4'],
[ 'B.A (Home Economics)','4'],
[ 'LLB (Law)','4'],
[ 'B.A (International Relations)','4'],
[ 'B.A (Library & Information Studies)','4'],
[ 'B.A (Myanmar Studies)','4'],
[ 'B.A (Public Policy)','4'],
[ 'B.A (Russian)','4'],
[ 'B.A (Tourism)','4'],
[ 'B.A SEAP Studies (SEAP)','4'],
[ 'B.A (Business Law)','4'],
[ 'B.A (EPP)','4'],
[ 'B.A (Environment Studies)','4'],
[ 'BTHM','4'],
[ 'BCom (Commerce)','4'],
[ 'BEcon (Economic) ','4'],
[ 'BEcon (Statistics)','4'],
[ 'B.Act','4'],
[ 'BB.A','4'],
[ 'BPS','4'],
[ 'BBM','4'],
[ 'BDevS','4'],
[ 'BPA','4'],
[ 'B.A (DSA)','4'],
[ 'BED','4'],
[ 'BED (Correspondence)','4'],
[ 'B.BSC (Bachelor of Business Science)','4'],
[ 'B.Sc (Biochemistry)','5'],
[ 'B.Sc (Botany)','5'],
[ 'B.Sc (Chem) ','5'],
[ 'B.Sc (Geology)','5'],
[ 'B.Sc (Maths)','5'],
[ 'B.Sc (Microbiology)','5'],
[ 'B.Sc (Physics)','5'],
[ 'B.Sc (Zoology)','5'],
[ 'B.Sc Eng (Informational Technology)','5'],
[ 'B.Sc Eng (IT.EC Double Diploma )','5'],
[ 'B.Sc Engineering (Cosmetic Technology)','5'],
[ 'B.Sc (Biotechnology)','5'],
[ 'B.Sc (Environmental Studies)','5'],
[ 'B.Sc (Environmental Science)','5'],
[ 'B.Sc (Industrial Chemistry)','5'],
[ 'B.Sc (Nuclear Physics)','5'],
[ 'B.Sc (Sport)','5'],
[ 'M.B.B.S','5'],
[ 'B.D.S','5'],
[ 'B.M.T.M','5'],
[ 'B.Sc (Apply Mathematics)','5'],
[ 'B.Sc (Nuclear Chemistry)','5'],
[ 'B.Sc (Electronic)','5'],
[ 'B.E (Marine)','5'],
[ 'B.E (Marine Electrical System and Electronics)','5'],
[ 'B.E (Aerospace - Propulsion and Flight Vehicles)','5'],
[ 'B.E (Aerospace -Avionics)','5'],
[ 'B.E (Aerospace - Electrical System and Instrumentation)','5'],
[ 'B.E (FP)','5'],
[ 'B.E (SS)','5'],
[ 'B.E (CE)','5'],
[ 'B.E (MPA)','5'],
[ 'B.E (MME)','5'],
[ 'B.E (Bio-T)','5'],
[ 'B.E (Hons) (CSE)','5'],
[ 'B.E (Hons) (ECE)','5'],
[ 'B.Ag','5'],
[ 'B.Agr.Sc','5'],
[ 'B.V.Sc','5'],
[ 'B.SC (Marine Science)','5'],
[ 'B.E (Mechatronics)','5'],
[ 'B.E (Chemical )','5'],
[ 'B.N.Sc','5'],
[ 'B.Pharm','5'],
[ 'B.Med.Tech (Medical Laboratory Technology)','5'],
[ 'B.Med.Tech (Medical Imaging Technology)','5'],
[ 'B.Med.Tech (Physiotherapy)','5'],
[ 'B.Med.Tech (Prosthetics & Orthetics)','5'],
[ 'B.E (Civil)','5'],
[ 'B.E (EP)','5'],
[ 'B.E (EC)','5'],
[ 'B.E (Mech)','5'],
[ 'B.E (McE)','5'],
[ 'B.E (IT)','5'],
[ 'B.E (CEIT)','5'],
[ 'B.E (Min)','5'],
[ 'B.E (ChE)','5'],
[ 'B.E (Tex)','5'],
[ 'B.E (PE)','5'],
[ 'B.E (Met)','5'],
[ 'B.E (NT)','5'],
[ 'B.E (Tele)','5'],
[ 'B.E (FT)','5'],
[ 'B.E (Agri)','5'],
[ 'B.Arch.','5'],
[ 'B.E (PV)','5'],
[ 'B.E (AV)','5'],
[ 'B.E (EI)','5'],
[ 'B.Sc (Forestry)','5'],
[ 'B.E (NA)','5'],
[ 'B.E (ME)','5'],
[ 'B.E (PH)','5'],
[ 'B.E (RC)','5'],
[ 'B.E (MSE)','5'],
[ 'B.E (Information Science and Technology)','5'],
[ 'B.Tech.(Civil)','5'],
[ 'B.Tech.(MP)','5'],
[ 'B.Tech.(EP)','5'],
[ 'B.Tech.(EC)','5'],
[ 'B.Sc (DSA)','5'],
[ 'B.C.Sc. (SE) ','6'],
[ 'B.C.Sc. (KE)','6'],
[ 'B.C.Tech. (NEW)','6'],
[ 'B.C.Tech. (CS)','6'],

[ 'B.C.Tech. (ESY)','6'],
[ 'B.C.Tech. (CN)','6'],
[ 'B.C.Sc. (BIS)','6'],
[ 'B.C.Sc. (HPC)','6'],
[ 'B.C.Sc. (CSF)','6'],
[ 'B.C.Tech. (CSS)','6'],
[ 'BPS(Hons)','7'],
[ 'BPA(Hons)','7'],
[ 'BDevs(Hons)','7'],
[ 'BEcon(Hons) (Statistics)','7'],
[ 'BEcon (Hons) (Economic)','7'],
[ 'BCom (Hons) (Commerce)','7'],
[ 'BBA(Hons)','7'],
[ 'B.A(Hons)(Musics)','7'],
[ 'B.Acts(Hons)','7'],
[ 'B.A(Hons)(Psychology)','7'],
[ 'B.A(Hons)(Philosophy)','7'],
[ 'B.A(Hons)(Dramatics Arts)','7'],
[ 'B.A(Hons)(Oriental Studies)','7'],
[ 'B.A(Hons)(Painting)','7'],
[ 'B.A(Hons)(Sculpture)','7'],
[ 'B.A(Hons)(Cinematography & Drama)','7'],
[ 'B.A(Hons)(Archaeology)','7'],
[ 'B.A(Hons)(International Relations)','7'],
[ 'B.A(Hons)(Myanmar)','7'],
[ 'B.A(Hons)(Creative Writing)','7'],
[ 'B.A(Hons)(History)','7'],
[ 'B.A(Hons)(Library & Information Studies)','7'],
[ 'B.Sc(Hons)(Industrial Chemistry)','8'],
[ 'B.Sc(Hons)(Environment Science)','8'],
[ 'B.Sc(Hons)(Sport)','8'],
[ 'B.Sc(Hons)(Biotechnology)','8'],
[ 'B.Sc(Hons)(Zoology)','8'],
[ 'B.Sc(Hons)(NS)','8'],
[ 'B.Sc(Hons)(Hydrology)','8'],
[ 'B.Sc(Hons)(Meteorodogy)','8'],
[ 'B.Sc(Hons)(Nuclear Physics)','8'],
[ 'B.Sc(Hons)(Computer Sciences)','8'],
[ 'B.Sc(Hons)(Marine Science)','8'],
[ 'B.Sc(Hons)(Biochemistry)','8'],
[ 'B.Sc(Hons)(Botany)','8'],
[ 'B.Sc(Hons)(Chemistry)','8'],
[ 'B.Sc(Hons)(Geology)','8'],
[ 'B.Sc(Hons)(Mathematics)','8'],
[ 'B.Sc(Hons)(Microbiology)','8'],
[ 'B.Sc(Hons)(Physics)','8'],
[ 'B.A(Hons)(Geography)','8'],
[ 'B.A(Hons)(Myanmar Studies)','8'],
[ 'B.A(Hons)(English)','8'],
[ 'LLB(Hons) (Law)','8'],
[ 'M.A (Myanmar)','9'],
[ 'M.A (English)','9'],
[ 'M.A (Geography)','9'],
[ 'M.A (History)','9'],
[ 'M.A (Oriental Studies)','9'],
[ 'M.A (Philosophy)','9'],
[ 'M.A (Psychology)','9'],
[ 'M.A (Anthropology)','9'],
[ 'M.A (Archaeology)','9'],
[ 'LLM(Law)','9'],
[ 'M.A (TEFM)','9'],
[ 'M.A Ed','9'],
[ 'M.Act','9'],
[ 'MBF ','9'],
[ 'MCom','9'],
[ 'MDevs','9'],
[ 'MPA','9'],
[ 'M.Econ(Statistics)','9'],
[ 'M.Econ(Economics)','9'],
[ 'MPS','9'],
[ 'MPhil(Botany)','9'],
[ 'MBA (Local)','9'],
[ 'MBA (Foreign)','9'],
[ 'MEd(Educational Methodology)','9'],
[ 'MEd(Education Theory)','9'],
[ 'MPhil(English)','9'],
[ 'Med(Educational Psychology)','9'],
[ 'MPhil(Geography)','9'],
[ 'Mphil(History)','9'],
[ 'Mphil(Industrial Chemistry)','9'],
[ 'Mphil(Psychology)','9'],
[ 'Mphil(Physics)','9'],
[ 'Mphil(Myanmar)','9'],
[ 'Mphil(Zoology)','9'],
[ 'M.A (French)','9'],
[ 'M.A (German)','9'],
[ 'M.A (International Relations)','9'],
[ 'M.A (Japanese)','9'],
[ 'M.A (Myanmar Studies)','9'],
[ 'M.A (Russian)','9'],
[ 'M.A SEAP Studies(SEAP)','9'],
[ 'M.A (Business Law)','9'],
[ 'M.A (Chinese)','9'],
[ 'M.A (Creative Writing)','9'],
[ 'M.A (Korean)','9'],
[ 'M.A (Library and Information Studies)','9'],
[ 'Mphil(Philosophy)','9'],
[ 'Mphil(Methematics)','9'],
[ 'Mphil(Chemistry)','9'],
[ 'MPhil','9'],
[ 'M.A (Defence Studies)','9'],
[ 'M.Sc(SE)','10'],
['M.Pharm','10'],
['M.Sc(Env.E)','10'],
['M.Sc(Env.M)','10'],
['M.Sc(GE)','10'],
['M.Sc(TE)','10'],
['M.Sc(RES)','10'],
['M.Sc(EcE)','10'],
['M.E(Marine Electrical System and Electronics)','10'],
['M.Sc(Tele)','10'],
['M.E (Marine)','10'],
['M.Sc(Bio.MET)','10'],
['M.E(Naval Architecture)','10'],
['M.Sc(TFT)','10'],
['M.Sc(Electronics)','10'],
['M.S.(EAM)','10'],
[ 'M.S.(Adapt.Met)','10'],
[ 'M.Sc(Nuclear Chemistry)','10'],
[ 'M.S.(Arc.Met)','10'],
[ 'M.Sc(Geology)','10'],
[ 'M.Sc(Mathematics)','10'],
[ 'M.Sc(Microbiology)','10'],
[ 'M.Sc(Physics)','10'],
[ 'M.Sc(Zoology)','10'],
[ 'M.Sc(Engineering Physics)','10'],
[ 'M.Sc(Apply Mathematics)','10'],
[ 'M.M.T.M','10'],
[ 'M.S.(E.Geol)','10'],
[ 'M.S.(Bio.T)','10'],
[ 'M.E.(Civil)','10'],
[ 'M.E.(CSE)','10'],
[ 'M.E.(CWRE)','10'],
[ 'M.E.(CGE)','10'],
[ 'M.Comm.H','10'],
[ 'M.E.(CTE)','10'],
[ 'M.E.(CM)','10'],
[ 'M.E.(Mech)','10'],
[ 'M.E.(EP)','10'],
[ 'M.E.(EC)','10'],
[ 'M.E.(IT)','10'],
[ 'M.E.(CEIT)','10'],
[ 'M.E.(McE)','10'],
[ 'M.E.(Chemical)','10'],
[ 'M.E.(Tex)','10'],
[ 'M.Sc(Biotechnology)','10'],
[ 'M.Sc(Engineering Mathematics)','10'],
[ 'M.Sc(Environmental Studies)','10'],
[ 'M.Sc(Nuclear Physics)','10'],
[ 'M.Sc(Industrial Chemistry)','10'],
[ 'M.E.(Mechatronics)','10'],
[ 'M.E.(Min)','10'],
[ 'M.E.(PE)','10'],
[ 'M.E.(Met)','10'],
[ 'M.E.(Adapt.Met)','10'],
[ 'M.E.(Ext.Met)','10'],
[ 'M.E.(ChE)','10'],
[ 'M.E.(NT)','10'],
[ 'M.Arch','10'],
[ 'M.F.T','10'],
[ 'M.E.(PV)','10'],
[ 'M.E.(AV)','10'],
[ 'M.E.(EI)','10'],
[ 'M.Agr.Sc','10'],
[ 'M.Sc(Forestry)','10'],
[ 'M.I.Sc','10'],
[ 'M.A.Sc','10'],
[ 'M.Sc(Forest Product)','10'],
[ 'M.Sc(Marine Science) ','10'],
[ 'M.Sc(Biochemistry)','10'],
[ 'M.Sc(Botany)','10'],
[ 'M.Sc(Chemistry)','10'],
['M.P.H','10'],
['M.H.A','10'],
['M.E.(Mechanical)','10'],
['M.C.Sc','11'],
['M.C.Tech','11'],
['M.E.(CS)','11'],
['M.C.Sc.(SE)','11'],
['M.C.Sc.(BIS)','11'],
['M.C.Sc.(KE)','11'],
['M.C.Sc.(HPC)','11'],
['M.C.Sc.(CSF)','11'],
['M.C.Tech.(NWK)','11'],
['M.C.Tech.(ES,ES)','11'],
['MRes(Anthropology)','12'],
['Mres(Archaeology)','12'],
['Mres(Computer Sciences)','12'],
['Mres(Creative Writing)','12'],
['Mres(International Relations)','12'],
['Mres(Law)','12'],
['Mres(Librart and Information Studies)','12'],
['Mres(Biotechnology)','12'],
['Mres(Environmental Studies)','12'],
['Mres(Industrial Chemistry)','12'],
['Mres(Myanmar)','12'],
['Mres(English)','12'],
['Mres(Marine Science)','12'],
['Mres(Biochemistry)','12'],
['Mres(Botany)','12'],
['MRes(Geography)','12'],
['Mres(Geology)','12'],
['Mres(Chemisty)','12'],
['Mres(History)','12'],
['Mres(Mathematics)','12'],
['Mres(Microbiology)','12'],
['Mres(Oriental Studies)','12'],
['Mres(Philosophy)','12'],
['MRes(Physics)','12'],
['Mres(Psychology)','12'],
['Mres(Zoology)','12'],
['Mres(Myanmar Studies)','12'],
['Mres(Nuclear Physics)','12'],
['Mres(Statistics)','12'],
['Ph.D.(Civil)','13'],
['Ph.D.(CSE)','13'],
['Ph.D.(CWRE)','13'],
['Ph.D.(CGE)','13'],
['Ph.D.(CTE)','13'],
['Ph.D.(CM)','13'],
['Ph.D.(CCE)','13'],
['Ph.D.(Env.S)','13'],
['Ph.D.(Myanmar)','13'],
['Ph.D.(Oriental Studies)','13'],
['Ph.D.(Philosophy)','13'],
['Ph.D.(Physics)','13'],
['Ph.D.(English)','13'],
['Ph.D.(Geography)','13'],
['Ph.D.(Geology)','13'],
['Ph.D.(Nanoscience and Nanotechnology)','13'],
['Ph.D.(EE)','13'],
['Ph.D.(IME)','13'],
['Ph.D.(TFE)','13'],
['Ph.D.(SSM)','13'],
['Ph.D.(Mech)','13'],
['Ph.D.(EP)','13'],
['Ph.D.(EC)','13'],
['Ph.D.(IT)','13'],
['Ph.D.(Psychology)','13'],
['Ph.D.(Statistics)','13'],
['Ph.D.(Zoology)','13'],
['Ph.D.(Marine Science)','13'],
['Ph.D.(Law)','13'],
['Ph.D.(Mathematics)','13'],
['Ph.D.(Nuclear Physics)','13'],
['Ph.D.(CEIT)','13'],
['Ph.D.(McE)','13'],
['Ph.D.(ChE)','13'],
['Ph.D.(Tex)','13'],
['Ph.D.(TF)','13'],
['Ph.D.(Mn)','13'],
['Ph.D.(PE)','13'],
['Ph.D.(Met)','13'],
['Ph.D.(Anthropology)','13'],
['Ph.D.(Archaeology)','13'],
['Ph.D.(Chinese)','13'],
['Ph.D.(Computer Sciences)','13'],
['Ph.D.(Law)','13'],
['Ph.D.(Mathematics)','13'],
['Ph.D.(Nuclear Physics)','13'],
['Ph.D.(Arch)','13'],
['Ph.D.(NT)','13'],
['Ph.D.(Bio-T)','13'],
['Ph.D.(IT)','13'],
['Ph.D.(Botany)','13'],
['Ph.D.(Chemistry)','13'],
['Ph.D.(Commerce)','13'],
['Ph.D.(Economics)','13'],
['Ph.D.(Industrial Chemistry)','13'],
['Ph.D.(Library ','13'],
['and Information Studies)','13'],
['Ph.D.(Apply Mathematics)','13'],
['Ph.D.(Nuclear Chemistry)','13'],
['Ph.D.(History)','13'],
['Ph.D.(Electronics)','13'],
['Ph.D.(Electronics)','13'],
['Doctor of Letters (Honoris Causa) (English)','14'],
['Doctor of Letters (Honoris Causa) (History)','14'],
['Doctor of Letters (Honoris Causa) (Myanmar)','14'],
['Doctor of Letters (Honoris Causa) (Zoology)','14'],
['Doctor of Letters (Honoris Causa) (Law)','14'],
['Doctor of Letters (Honoris Causa) (Mathematics)','14'],
['Doctor of Letters (Honoris Causa) (Oriental Studies)','14'],
['Doctor of Letters (Honoris Causa) (Philosophy)','14'],
['Doctor of Letters (Honoris Causa) (Psychology)','14'],
['AGTI(Civil)','15'],
['AGTI(EC)','15'],
['AGTI(EP)','15'],
['AGTI(Mech)','15'],
['AGTI(IT)','15'],
['AGTI(IE)','15'],
['AGTI(FM)','15'],
['AGTI(ATM)','15'],
['AGTI(EEI)','15'],
['GTHS(BT)','15'],
['GTHS(EcT)','15'],
['GTHS(ET)','15'],
['GTHS(AT)','15'],
['GTHS(MT)','15'],
['GTHS(BST)','15'],
['GTHS(MPT)','15'],
['GTHS(IT)','15'],
['Dip; IT','15'],
['Dip; C.Sc','15'],
['Dip; A.B.S','15'],
['Dip; (Foresty)','15'],
['Dip; (NS)','15'],
['Dip; (Mar.Tech)','15'],
['Dip; (SE)','15'],
['Dip; (BM)','15'],
['Dip; (ED)','15'],
['Dip; (BFI)','15'],
['Dip; (FM)','15'],
['Dip; (BA)','15'],
['PGD(NE)','15'],
['PGD(SD)','15'],
['PGD(CSE)','15'],
['PGD(WRE)','15'],
['PGD(Env.E)','15'],
['PGD(Env.M)','15'],
['PGD(CGE)','15'],
['PGD(CM)','15'],
['PGD(CTE)','15'],
['PGD(CA)','15'],
['PGD(RE)','15'],
['PGD(MA)','15'],
['PGD(IE)','15'],
['PGD(RES)','15'],
['PGD(AA)','15'],
['PGD(EcE)','15'],
['Dip; (MM)','15'],
['Dip; (LWT)','15'],
['Dip; (Buddha Damma)','15'],
['AGTI(MP)','15'],
['Dip; RS','15'],
['Dip; S','15'],
['Dip; SE','15'],
['Dip; APsy','15'],
['Dip; BL','15'],
['Dip; IL','15'],
['Dip; ELT','15'],
['Dip; (English)','15'],
['Dip; IR','15'],
['Dip; OS','15'],
['Dip; PS','15'],
['Dip; TSM','15'],
['Dip; DS','15'],
['Dip; AA','15'],
['Dip; B','15'],
['Dip; EM','15'],
['Dip; ES','15'],
['Dip; ELTM','15'],
['Dip; (Chinese)','15'],
['Dip; (French)','15'],
['Dip; (German)','15'],
['Dip; (Italian)','15'],
['Dip; (Japanese)','15'],
['Dip; (Korean)','15'],
['Dip; (Myanmar)','15'],
['PGD(Tele)','15'],
['PGD(Russian)','15'],
['PGD(Bio.MET)','15'],
['PGD(Korean)','15'],
['PGD(Tex)','15'],
['PGD(EIA/EMS)','15'],
['PGD(Japanese)','15'],
['PGD(FT)','15'],
['PGD(German)','15'],
['PGD(Arc.Met)','15'],
['PGD(Ext.Met)','15'],
['PGD(French)','15'],
['PGD(Adapt.Met)','15'],
['PGD(E.Geol)','15'],
['PGD(Chinese)','15'],
['PGD(SSSE)','15'],
['Dip; (Russian)','15'],
['Dip; (Thai)','15'],
['Dip; (Anthropology)','15'],
['Dip; (Apply Geology)','15'],
['Dip; (Apply Physics)','15'],
['Dip; (Geology)','15'],
['Dip; (IL)','15'],
['Dip; (IR)','15'],
['Dip; (Law)','15'],
['Dip; (ML)','15'],
['Dip; (DTSM) (Myanmar)','15'],
['Dip; (EDCS) WBTS','15'],
['Dip; (ELT)','15'],
['Dip; (GIS)','15'],
['Dip; (Library and Information Studies)','15'],
['Dip; (DPCS)','15'],
['Dip; Industrial Chemistry (Food Technology)','15'],
['Dip; (Apply Psychology)','15'],
['Dip; (Archaeology)','15'],
['Dip; (Social Work)','15'],
['Dip; (Management and Administration)','15'],
['AGDI(MT&DE)','15'],
['AGDI(Electronic)','15'],
['AGDI(ME)','15'],
['AGDI(S&H)','15'],
['AGDI(Metallurgical Engineering)','15'],
['AGDI(Chem)','15'],
['Dip; Cs','15'],
['PGD(WE)','15'],
['PGD(Global)','15'],
['PGD(Sculpture)','15'],
['PGD(Arg.S)','15'],
['PGD(SM)','15'],
['PGD(Painting)','15'],
['PGD(PM)','15'],
['PGD(Museology)','15'],
['PGD(Dramatic Art)','15'],
['PGD(Applied Archaeology)','15'],
['PGD(Music)','15'],
['ADCSM','15'],
['CPA','15'],
['DA','15'],
['M.E','15'],
['PGDCA','5'],
['B.C.SC(DSA)','2'],
['M.Sc(Engg:&Tech)','5'],
['B.E(Electrical Power)(DSTA)','5'],

];
foreach($items as $item){
    Education::create(array_combine($columns,$item));
}

    }
}
