<?php

namespace Database\Seeders;
use Illuminate\Support\Facades\DB;


use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class TownshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $townships = [
            ['id' => '228', 'name' => 'ကျောက်တန်း', 'district_id' => '88'],
            ['id' => '229', 'name' => 'သုံးခွ', 'district_id' => '88'],
            ['id' => '230', 'name' => 'ခရမ်း', 'district_id' => '88'],
            ['id' => '231', 'name' => 'ကိုကိုးကျွန်း', 'district_id' => '88'],
            ['id' => '232', 'name' => 'တွံတေး', 'district_id' => '89'],
            ['id' => '233', 'name' => 'ဆိပ်ကြီး/ခနောင်တို', 'district_id' => '89'],
            ['id' => '234', 'name' => 'ဒလ', 'district_id' => '89'],
            ['id' => '235', 'name' => 'ကော့မှူး', 'district_id' => '89'],
            ['id' => '236', 'name' => 'ကွမ်းခြံကုန်း', 'district_id' => '89'],
            ['id' => '237', 'name' => 'ကျောက်တံတား', 'district_id' => '90'],
            ['id' => '238', 'name' => 'ပန်းဘဲတန်း', 'district_id' => '90'],
            ['id' => '239', 'name' => 'လသာ', 'district_id' => '90'],
            ['id' => '240', 'name' => 'လမ်းမတော်', 'district_id' => '90'],
            ['id' => '241', 'name' => 'ဒဂုံ', 'district_id' => '90'],
            ['id' => '242', 'name' => 'အလုံ', 'district_id' => '91'],
            ['id' => '243', 'name' => 'ကြည့်မြင့်တိုင်', 'district_id' => '91'],
            ['id' => '244', 'name' => 'စမ်းချောင်း', 'district_id' => '91'],
            ['id' => '245', 'name' => 'မရမ်းကုန်း', 'district_id' => '92'],
            ['id' => '246', 'name' => 'လှိုင်', 'district_id' => '92'],
            ['id' => '247', 'name' => 'မြောက်ဥက္ကလာပ', 'district_id' => '92'],
            ['id' => '248', 'name' => 'ကမာရွတ်', 'district_id' => '93'],
            ['id' => '249', 'name' => 'ဗဟန်း', 'district_id' => '93'],
            ['id' => '250', 'name' => 'မက်မန်း', 'district_id' => '94'],
            ['id' => '251', 'name' => 'ပန်ဆန်း(ပန်ခမ်း)', 'district_id' => '94'],
            ['id' => '252', 'name' => 'နားဖန်း', 'district_id' => '94'],
            ['id' => '253', 'name' => 'ဟိုပန်', 'district_id' => '95'],
            ['id' => '254', 'name' => 'မိုင်းမော', 'district_id' => '95'],
            ['id' => '255', 'name' => 'ပန်ဝိုင်', 'district_id' => '95'],
            ['id' => '256', 'name' => 'ရွာငံ', 'district_id' => '96'],
            ['id' => '257', 'name' => 'ပင်းတယ', 'district_id' => '96'],
            ['id' => '258', 'name' => 'ဟိုပုံး', 'district_id' => '97'],
            ['id' => '259', 'name' => 'ဆီဆိုင်', 'district_id' => '97'],
            ['id' => '260', 'name' => 'ပင်လောင်း', 'district_id' => '97'],
            ['id' => '261', 'name' => 'နမ့်ဆန်', 'district_id' => '98'],
            ['id' => '262', 'name' => 'မန်တုံ', 'district_id' => '98'],
            ['id' => '263', 'name' => 'ကုန်းကြမ်း', 'district_id' => '99'],
            ['id' => '264', 'name' => 'လောက်ကိုင်', 'district_id' => '99'],
            ['id' => '265', 'name' => 'ကျောက်မဲ', 'district_id' => '100'],
            ['id' => '266', 'name' => 'နမ္မတူ', 'district_id' => '100'],
            ['id' => '267', 'name' => 'နောင်ချို', 'district_id' => '100'],
            ['id' => '268', 'name' => 'သီပေါ', 'district_id' => '100'],
            ['id' => '269', 'name' => 'ကျိုင်းတုံ', 'district_id' => '101'],
            ['id' => '270', 'name' => 'မိုင်းခတ်', 'district_id' => '101'],
            ['id' => '271', 'name' => 'မိုင်းပျဥ်း', 'district_id' => '101'],
            ['id' => '272', 'name' => 'မိုင်းယန်း', 'district_id' => '102'],
            ['id' => '273', 'name' => 'မိုင်းလား', 'district_id' => '103'],
            ['id' => '274', 'name' => 'တာချီလိတ်', 'district_id' => '104'],
            ['id' => '275', 'name' => 'မိုင်းဖြတ်', 'district_id' => '104'],
            ['id' => '276', 'name' => 'မိုင်းယောင်း', 'district_id' => '105'],
            ['id' => '277', 'name' => 'တောင်ကြီး', 'district_id' => '106'],
            ['id' => '278', 'name' => 'ရပ်စောက်', 'district_id' => '106'],
            ['id' => '279', 'name' => 'ကလော', 'district_id' => '107'],
            ['id' => '280', 'name' => 'ညောင်ရွှေ', 'district_id' => '107'],
            ['id' => '281', 'name' => 'ဖယ်ခုံ', 'district_id' => '107'],
            ['id' => '282', 'name' => 'မူဆယ်', 'district_id' => '108'],
            ['id' => '283', 'name' => 'နန့်ခမ်း', 'district_id' => '108'],
            ['id' => '284', 'name' => 'ကွတ်ခိုင်', 'district_id' => '109'],
            ['id' => '285', 'name' => 'မဘိမ်း', 'district_id' => '110'],
            ['id' => '286', 'name' => 'မိုးမိတ်', 'district_id' => '110'],
            ['id' => '287', 'name' => 'မိုင်းဆတ်', 'district_id' => '111'],
            ['id' => '288', 'name' => 'မိုင်းတုံ', 'district_id' => '112'],
            ['id' => '289', 'name' => 'လာရှိုး', 'district_id' => '113'],
            ['id' => '290', 'name' => 'သိန္နီ', 'district_id' => '113'],
            ['id' => '291', 'name' => 'ကွမ်းလုံ', 'district_id' => '113'],
            ['id' => '292', 'name' => 'တန့်ယန်း', 'district_id' => '114'],
            ['id' => '293', 'name' => 'မိုင်းရယ်', 'district_id' => '114'],
            ['id' => '294', 'name' => 'လင်းခေး', 'district_id' => '115'],
            ['id' => '295', 'name' => 'မောက်မယ်', 'district_id' => '115'],
            ['id' => '296', 'name' => 'မိုင်းပန်', 'district_id' => '115'],
            ['id' => '297', 'name' => 'လွိုင်လင်', 'district_id' => '116'],
            ['id' => '298', 'name' => 'လဲချား', 'district_id' => '116'],
            ['id' => '299', 'name' => 'မိုင်းကိုင်', 'district_id' => '116'],
            ['id' => '300', 'name' => 'နမ့်စန်', 'district_id' => '117'],
            ['id' => '301', 'name' => 'ကွန်ဟိန်း', 'district_id' => '117'],
            ['id' => '302', 'name' => 'မိုးနဲ', 'district_id' => '117'],
            ['id' => '303', 'name' => 'မိုင်းရှုး', 'district_id' => '118'],
            ['id' => '304', 'name' => 'ကျေးသီး', 'district_id' => '118'],
            ['id' => '305', 'name' => 'ပုသိမ်', 'district_id' => '119'],
            ['id' => '306', 'name' => 'ကန်ကြီးထောင့်', 'district_id' => '119'],
            ['id' => '307', 'name' => 'သာပေါင်း', 'district_id' => '119'],
            ['id' => '308', 'name' => 'ငပုတော', 'district_id' => '119'],
            ['id' => '309', 'name' => ' ကျုံပျော်', 'district_id' => '120'],
            ['id' => '310', 'name' => 'ရေကြည်', 'district_id' => '120'],
            ['id' => '311', 'name' => 'ကျောင်းကုန်း', 'district_id' => '120'],
            ['id' => '312', 'name' => 'ကျိုက်လတ်', 'district_id' => '121'],
            ['id' => '313', 'name' => 'ဒေးဒရဲ', 'district_id' => '121'],
            ['id' => '314', 'name' => 'ဖျာပုံ', 'district_id' => '121'],
            ['id' => '315', 'name' => 'ဘိုကလေး', 'district_id' => '121'],
            ['id' => '316', 'name' => 'ညောင်တုန်း', 'district_id' => '122'],
            ['id' => '317', 'name' => 'ဓနုဖြူ', 'district_id' => '122'],
            ['id' => '318', 'name' => 'ပန်းတနော်', 'district_id' => '122'],
            ['id' => '319', 'name' => 'မအူပင်', 'district_id' => '122'],
            ['id' => '320', 'name' => 'မြောင်းမြ', 'district_id' => '123'],
            ['id' => '321', 'name' => 'ဝါးခယ်မ', 'district_id' => '123'],
            ['id' => '322', 'name' => 'အိမ်မဲ', 'district_id' => '123'],
            ['id' => '323', 'name' => 'မော်လမြိုင်ကျွန်း', 'district_id' => '124'],
            ['id' => '324', 'name' => 'လပွတ္တာ', 'district_id' => '124'],
            ['id' => '325', 'name' => 'ဟင်္သာတ', 'district_id' => '125'],
            ['id' => '326', 'name' => 'ဇလွန်', 'district_id' => '125'],
            ['id' => '327', 'name' => 'လေးမျက်နှာ', 'district_id' => '125'],
            ['id' => '328', 'name' => 'မြန်အောင်', 'district_id' => '126'],
            ['id' => '329', 'name' => 'ကြံခင်း', 'district_id' => '126'],
            ['id' => '330', 'name' => 'အင်္ဂပူ', 'district_id' => '126'],
        ];

        DB::table('townships')->insert($townships);
    }
}
